version: '3'
services:
  mysql_rdbms:
    image: docker.wso2.com/ei-pattern4-rdbms:6.1.1
    build:
      context: ../
      dockerfile: pattern-4/database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
  broker:
    image: docker.wso2.com/ei-pattern4-wso2ei-broker:6.1.1
    build:
      context: ../
      dockerfile: pattern-4/broker/Dockerfile
    environment:
      - SLEEP=100
    ports:
      - "9446:9446"
      - "9766:9766"
      - "1886:1886"
      - "8886:8886"
      - "5675:5675"
      - "8675:8675"
      - "7614:7614"
