version: '3'
services:
  mysql_rdbms:
    image: docker.wso2.com/ei-pattern3-rdbms:6.1.1
    build:
      context: ../
      dockerfile: pattern-3/database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
  business-process:
    image: docker.wso2.com/ei-pattern3-wso2ei-business-process:6.1.1
    build:
      context: ../
      dockerfile: pattern-3/business-process/Dockerfile
    environment:
      - SLEEP=30
    ports:
      - "9445:9445"
      - "9765:9765"
