version: '2.3'
services:
  wso2ei-mysql:
    image: mysql:5.7.20
    container_name: wso2ei-mysql
    hostname: wso2ei-mysql
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      # mounting MySQL init scripts
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      # mounting MySQL DB data
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
  wso2ei-analytics:
    image: docker.wso2.com/wso2ei-analytics:6.2.0
    container_name: wso2ei-analytics
    hostname: wso2ei-analytics
    ports:
      - 9444:9444
      - 9612:9612
      - 9712:9712
      - 7712:7712
      - 7612:7612
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9444/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      # mounting configurations
      - ./analytics/conf/datasources/master-datasources.xml:/home/wso2carbon/volumes/conf/datasources/master-datasources.xml
      - ./analytics/conf/registry.xml:/home/wso2carbon/volumes/conf/registry.xml
      - ./analytics/conf/user-mgt.xml:/home/wso2carbon/volumes/conf/user-mgt.xml
      - ./analytics/conf/carbon.xml:/home/wso2carbon/volumes/conf/carbon.xml
      - ./analytics/conf/datasources/analytics-datasources.xml:/home/wso2carbon/volumes/conf/datasources/analytics-datasources.xml
      # mounting keystores
      - ./analytics/repository/resources/security/wso2carbon.jks:/home/wso2carbon/volumes/repository/resources/security/wso2carbon.jks
      - ./analytics/repository/resources/security/client-truststore.jks:/home/wso2carbon/volumes/repository/resources/security/client-truststore.jks
    depends_on:
      wso2ei-mysql:
        condition: service_healthy
    links:
      - wso2ei-mysql
  wso2ei-business-process:
    image: docker.wso2.com/wso2ei-business-process:6.2.0
    container_name: wso2ei-business-process
    hostname: wso2ei-business-process
    ports:
      - 9445:9445
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9445/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s
    volumes:
      # mounting configurations
      - ./business-process/conf/datasources/master-datasources.xml:/home/wso2carbon/volumes/conf/datasources/master-datasources.xml
      - ./business-process/conf/datasources/bps-datasources.xml:/home/wso2carbon/volumes/conf/datasources/bps-datasources.xml
      - ./business-process/conf/datasources/activiti-datasources.xml:/home/wso2carbon/volumes/conf/datasources/activiti-datasources.xml
      - ./business-process/conf/etc/tasks-config.xml:/home/wso2carbon/volumes/conf/etc/tasks-config.xml
      - ./business-process/conf/registry.xml:/home/wso2carbon/volumes/conf/registry.xml
      - ./business-process/conf/carbon.xml:/home/wso2carbon/volumes/conf/carbon.xml
      - ./business-process/conf/user-mgt.xml:/home/wso2carbon/volumes/conf/user-mgt.xml
      - ./business-process/conf/bps.xml:/home/wso2carbon/volumes/conf/bps.xml
      # mounting keystores
      - ./business-process/repository/resources/security/wso2carbon.jks:/home/wso2carbon/volumes/repository/resources/security/wso2carbon.jks
      - ./business-process/repository/resources/security/client-truststore.jks:/home/wso2carbon/volumes/repository/resources/security/client-truststore.jks
    depends_on:
      wso2ei-mysql:
        condition: service_healthy
      wso2ei-analytics:
        condition: service_healthy
    links:
      - wso2ei-mysql
      - wso2ei-analytics
  wso2ei-integrator:
    image: docker.wso2.com/wso2ei-integrator:6.2.0
    container_name: wso2ei-integrator
    hostname: wso2ei-integrator
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 120s
    volumes:
      # mounting configurations
      - ./integrator/conf/datasources/master-datasources.xml:/home/wso2carbon/volumes/conf/datasources/master-datasources.xml
      - ./integrator/conf/user-mgt.xml:/home/wso2carbon/volumes/conf/user-mgt.xml
      - ./integrator/conf/registry.xml:/home/wso2carbon/volumes/conf/registry.xml
      - ./integrator/conf/synapse.properties:/home/wso2carbon/volumes/conf/synapse.properties
      - ./integrator/conf/axis2/axis2.xml:/home/wso2carbon/volumes/conf/axis2/axis2.xml
      # mounting carbon apps
      - ./integrator/repository/deployment/server/carbonapps:/home/wso2carbon/volumes/repository/deployment/server/carbonapps
      # mounting analytics event publishers
      - ./integrator/repository/deployment/server/eventpublishers:/home/wso2carbon/volumes/repository/deployment/server/eventpublishers
      # mounting synapse artifacts
      - ./integrator/repository/deployment/server/synapse-configs:/home/wso2carbon/volumes/repository/deployment/server/synapse-configs
      # mounting keystores
      - ./integrator/repository/resources/security/wso2carbon.jks:/home/wso2carbon/volumes/epository/resources/security/wso2carbon.jks
      - ./integrator/repository/resources/security/client-truststore.jks:/home/wso2carbon/volumes/repository/resources/security/client-truststore.jks
    depends_on:
      wso2ei-mysql:
        condition: service_healthy
      wso2ei-analytics:
        condition: service_healthy
      wso2ei-business-process:
        condition: service_healthy
    links:
      - wso2ei-mysql
      - wso2ei-analytics
      - wso2ei-business-process
