version: '3'
services:
  mysql_rdbms:
    image: docker.wso2.com/ei-pattern10-rdbms:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
  broker1:
    image: docker.wso2.com/ei-pattern10-wso2ei-broker-node1:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/broker1/Dockerfile
    environment:
      - SLEEP=30
    ports:
      - "1886:1886"
      - "8886:8886"
      - "5675:5675"
      - "8675:8675"
    depends_on:
      - "mysql_rdbms"
  broker2:
    image: docker.wso2.com/ei-pattern10-wso2ei-broker-node2:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/broker2/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "1887:1886"
      - "8887:8886"
      - "5676:5675"
      - "8676:8675"
    depends_on:
      - "mysql_rdbms"
      - "broker1"
  analytics1:
    image: docker.wso2.com/ei-pattern10-wso2ei-analytics-node1:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/analytics1/Dockerfile
    environment:
      - SLEEP=30
    depends_on:
      - "mysql_rdbms"
  analytics2:
    image: docker.wso2.com/ei-pattern10-wso2ei-analytics-node2:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/analytics2/Dockerfile
    environment:
      - SLEEP=90
    depends_on:
      - "mysql_rdbms"
      - "analytics1"
  integrator1:
    image: docker.wso2.com/ei-pattern10-wso2ei-node1:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/integrator1/Dockerfile
    environment:
      - SLEEP=120
    depends_on:
      - "mysql_rdbms"
      - "analytics1"
      - "analytics2"
      - "broker1"
      - "broker2"
  integrator2:
    image: docker.wso2.com/ei-pattern10-wso2ei-node2:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/integrator2/Dockerfile
    environment:
      - SLEEP=150
    depends_on:
      - "mysql_rdbms"
      - "analytics1"
      - "analytics2"
      - "broker1"
      - "broker2"
      - "integrator1"
  nginx:
    image: docker.wso2.com/ei-pattern10-nginx:6.1.1
    build:
      context: ../
      dockerfile: pattern-10/nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - "analytics1"
      - "analytics2"
      - "broker1"
      - "broker2"
      - "integrator1"
      - "integrator2"
