version: '3'
services:
  mysql_rdbms:
    image: docker.wso2.com/ei-pattern2-rdbms:6.1.1
    build:
      context: ../
      dockerfile: pattern-2/database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
  analytics:
    image: docker.wso2.com/ei-pattern2-wso2ei-analytics:6.1.1
    build:
      context: ../
      dockerfile: pattern-2/analytics/Dockerfile
    environment:
      - SLEEP=30
    ports:
      - "9444:9444"
      - "9764:9764"
      - "9612:9612"
      - "9712:9712"
      - "7612:7612"
      - "7712:7712"
    depends_on:
      - "mysql_rdbms"
  integrator:
    image: docker.wso2.com/ei-pattern2-wso2ei:6.1.1
    build:
      context: ../
      dockerfile: pattern-2/integrator/Dockerfile
    environment:
      - SLEEP=90
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8280:8280"
      - "8243:8243"
    depends_on:
      - "mysql_rdbms"
      - "analytics"
