version: '3'
services:
  mysql_rdbms:
    image: docker.wso2.com/ei-pattern7-rdbms:6.1.1
    build:
      context: ../
      dockerfile: pattern-7/database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
  business-process1:
    image: docker.wso2.com/ei-pattern7-wso2ei-business-process-node1:6.1.1
    build:
      context: ../
      dockerfile: pattern-7/business-process1/Dockerfile
    environment:
      - SLEEP=30
    depends_on:
      - "mysql_rdbms"
  business-process2:
    image: docker.wso2.com/ei-pattern7-wso2ei-business-process-node2:6.1.1
    build:
      context: ../
      dockerfile: pattern-7/business-process2/Dockerfile
    environment:
      - SLEEP=60
    depends_on:
      - "mysql_rdbms"
      - "business-process1"
  nginx:
    image: docker.wso2.com/ei-pattern7-nginx:6.1.1
    build:
      context: ../
      dockerfile: pattern-7/nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - "business-process1"
      - "business-process2"
