version: '3'
services:
  mysql_rdbms:
    image: docker.wso2.com/ei-pattern8-rdbms:6.1.1
    build:
      context: ../
      dockerfile: pattern-8/database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
  broker1:
    image: docker.wso2.com/ei-pattern8-wso2ei-broker-node1:6.1.1
    build:
      context: ../
      dockerfile: pattern-8/broker1/Dockerfile
    environment:
      - SLEEP=30
    ports:
      - "1886:1886"
      - "8886:8886"
      - "5675:5675"
      - "8675:8675"
    depends_on:
      - "mysql_rdbms"
  broker2:
    image: docker.wso2.com/ei-pattern8-wso2ei-broker-node2:6.1.1
    build:
      context: ../
      dockerfile: pattern-8/broker2/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "1887:1886"
      - "8887:8886"
      - "5676:5675"
      - "8676:8675"
    depends_on:
      - "mysql_rdbms"
      - "broker1"
  nginx:
    image: docker.wso2.com/ei-pattern8-nginx:6.1.1
    build:
      context: ../
      dockerfile: pattern-8/nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - "broker1"
      - "broker2"
